### PR TITLE
Adding out of sync warning

### PR DESCRIPTION
**Pull request by evertonfraga**
- Adds note about out-of-sync issue
- Adds a button at right with a shortcut to etherscan, so people can quickly validate their balances

image

I'd appreciate any help translating to the following languages :)
- [x] de
- [x] en
- [ ] es
- [ ] fr
- [ ] ja
- [ ] ko
- [x] pt
- [ ] ro
- [ ] ru
- [ ] ua
- [ ] zh-TW
- [ ] zh

### CODE REVIEW

**Comment by luclu** [comment]
Perhaps the warning should only show under some condition like:
`180 < (new Date().getTime()/1000 - web3.eth.getBlock(web3.eth.blockNumber).timestamp)`
i.e. "last block is older than 3 minutes"

Can you think of any drawback in this?

**Comment by frozeman** [comment]
Sync calling is a no go, so the could would be a bit more complicated than the above.

**Comment by evertonfraga** [comment]
Can I get your approval, guys? we can leave the other translations for the community

**Comment by lordofangels** [comment]
Everton, good morning. I've created an issue #2192 and I cannot reopen it. You answered it. I am in Brazil too (estado do Paraná). Could it you see it? Another question: what is the main help that you need in this issue #374? The translation or the code? Um bom dia

**Comment by evertonfraga** [comment]
@frozeman @alexvandesande 
I think we're good to go. Could you merge, as I don't have access anymore? Thanks

**Pull request merged**
