### PR TITLE
Add of Albanian (al) and Italian (it) languages

### PR DESCRIPTION
**Pull request by h2002al**
Proposal to add the translation of two languages for the ether wallet.

### CODE REVIEW

**Comment by alexvandesande** [comment]
I don't see where you added the translations themselves..

**Comment by alexvandesande** [comment]
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/app.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/wallet.en.i18n.json

**Comment by h2002al** [comment]
Have you found the translations Alex? Are two translations (Albanian and
Italian) of this file:


https://github.com/ethereum/mist/blob/develop/interface/
i18n/app.en.i18n.json

I am working with the second one send by you. Time after time you will see
other work added. But the above is done (except three words which need the
context). In Albanian and Italian. Tell me if everything is ok.

Roland



[image: --]

Roland Kajca
[image: https://]about.me/rolandkajca
<https://about.me/rolandkajca?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by alexvandesande** [comment]
I merged the Mist translations changes. I still need these files for the wallet translation. Thanks Roland!

https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/app.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/wallet.en.i18n.json

**Comment by h2002al** [comment]
Are yet to much to do Alex.

link 1 (needed three contexts to be finished (both languages) in albanian
and italian)
link 2 (yet to be finished the translation in Albanian - very few to do -
and to be made all the translation in Italian)

In few words is made only half of the work for the first two links. Then
needed to be made all the work for the other two links.


I send you an email with need for explanations.



[image: --]

Roland Kajca
[image: https://]about.me/rolandkajca
<https://about.me/rolandkajca?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

On Fri, May 13, 2016 at 3:31 PM, Alex Van de Sande <notifications@github.com

**Comment by h2002al** [comment]
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

You&#39;ve been officially invited to Roland Kajca&#39;s circle of trust.

Accept your invitation &#9658;

Don&#39;t know Roland Kajca? View their photos or see who else you know in their circle of trust before accepting.

*This offer has been sent by rolandkajca@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by alexvandesande** [comment]
closing due to inactivity. Feel ready to open a new PR once you are ready for it.

**Pull request closed without merging**
