### PR TITLE
Ethereum-Wallet doesn't show me my Balance. 

### PR DESCRIPTION
**Pull request by Martymau91**
I've transfer some ether from a internet account to Ethereum-wallet. After more then 12h I cannot see the ethers on my wallet but the transaction is done and I can see it by internet.

Is some one can help with this. I think the wallet is not sync or I really don't know. 

Thanks so musch

M

### CODE REVIEW

**Comment by alexvandesande** [comment]
Thanks for the typo fix, I've added it manually to a development branch. But it seems that you are using this also to report an issue which is not the right way to do it.

As to you issue, your wallet needs to sync completely. Please make sure your clock is in sync with an international time server and you have enough peers and then just wait for the sync to finish

**Comment by Martymau91** [comment]
sorry for this and thank for reply,

But even if on the Mist I;ve transfered on Test-Net network?

**Comment by alexvandesande** [comment]
Did you transfer your ether into a testnet account?

**Comment by Martymau91** [comment]
Yes, and now i can see my ethers, thank you so much, can i have your address to donate?

Many thanks

M

Inviato da iPhone

**Comment by alexvandesande** [comment]
You're welcome. I don't take donations but you can buy yourself a unicorn at ethereum.org/donate

**Comment by Martymau91** [comment]
Thanks a lot.

Inviato da iPhone

> Il giorno 15 Mar 2016, alle ore 18:52, Alexandre Van de Sande <notifications@github.com> ha scritto:
> 
> You're welcome. I don't take donations but you can buy yourself a unicorn at ethereum.org/donate 
> 
> 
>

**Pull request closed without merging**
