### PR TITLE
Fix stuck creating wallets on LES

### PR DESCRIPTION
**Pull request by evertonfraga**
This PR fixes the creation of wallet contracts while using the Light Client.

It gets wallets that has transaction hash and does not have addresses and performs a getTransactionReceipt, trying to find that particular address.

It'll only work after https://github.com/ethereum/mist/pull/3265 has been released.

### CODE REVIEW

**Comment by stbregeon** [comment]
@evertonfraga 
Thank you very much, very great job.

I'm not very used yet with the Ethereum wallet. How can I use these path ? or is it beter that I wait for the update ?

**Comment by evertonfraga** [comment]
@stbregeon if you feel comfortable, you can make use of these two guides:
https://github.com/ethereum/mist#development
https://github.com/ethereum/meteor-dapp-wallet#development

Otherwise, we're planning a release for early next week.

**Comment by stbregeon** [comment]
@evertonfraga
thank you very much.

**Comment by Hasbullah110782** [comment]
Bisakah  saya Menganti dompet vinchainwallet kedompet resmi

**Pull request merged**
