### PR TITLE
Fixes incorrect total token balance

### PR DESCRIPTION
**Pull request by alexvandesande**
Fixes https://github.com/ethereum/mist/issues/608

I'm separating a part of https://github.com/ethereum/meteor-dapp-wallet/pull/196/ into this independent PR

### CODE REVIEW

**Comment by hiddentao** [comment]
Needs rebasing against develop.

**Comment by hiddentao** [comment]
Token balance looks right to me.

**Comment by billprescott** [comment]
Everytime you add a watch contract for The DAO the Watch Token increases. Delete the watch contract and add again and it just keeps adding the tokens to the previous balance.

**Comment by alexvandesande** [comment]
@billprescott I couldn't reproduce this bug

**Pull request merged**
